name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        clang-version:
          - 15
    steps:
      - name: Install clang-${{ matrix.clang-version }}
        uses: egor-tensin/setup-clang@v1
        with:
          version: ${{ matrix.clang-version }}
      - name: Set clang-${{ matrix.clang-version }} as default
        run: |
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-${{ matrix.clang-version }} 999
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-${{ matrix.clang-version }} 999
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-${{ matrix.clang-version }} 999
          sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-${{ matrix.clang-version }} 999
          sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang-${{ matrix.clang-version }} 999
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-${{ matrix.clang-version }} 999
      - uses: lukka/get-cmake@v3.22.2
      - uses: actions/checkout@v4
      - name: clang-format
        run: clang-format --dry-run --Werror --style=file $(find include/ -name '*.hpp') $(find src/ -name '*.cpp')
      - run: make
      - run: make tidy
      - run: make test

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install CMake
        run: |
          choco install cmake
          cmake --version
      - name: Install Ninja
        run: |
          choco install ninja
          ninja --version
      - name: cmake
        run: |
          cmake -G "Ninja" -B build
      - name: ninja
        run: |
          ninja -C build
      - name: Run tests
        run: build\Debug\tests\unit_tests_shm.exe
